spring.datasource.url=jdbc:postgresql://localhost:5432/bankappsimu
spring.datasource.username=gsig
spring.datasource.password=br@123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
